CREATE DATABASE IF NOT EXISTS pghostel;
USE pghostel;

-- Tables are generated by Spring Boot/JPA.
-- Sharing types:
-- ONE   = 1 Sharing = capacity 1
-- TWO   = 2 Sharing = capacity 2
-- THREE = 3 Sharing = capacity 3
